// Curated Hitster-style song deck: title, artist, and true release year of the single.
const SONGS = [
  { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1954 },
  { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
  { title: "That'll Be the Day", artist: "Buddy Holly", year: 1957 },
  { title: "I Want to Hold Your Hand", artist: "The Beatles", year: 1963 },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Hey Jude", artist: "The Beatles", year: 1968 },
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { title: "Hotel California", artist: "Eagles", year: 1976 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Like a Virgin", artist: "Madonna", year: 1984 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "Bye Bye Bye", artist: "NSYNC", year: 2000 },
  { title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
  { title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Empire State of Mind", artist: "Jay-Z", year: 2009 },
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011 },
  { title: "Get Lucky", artist: "Daft Punk", year: 2013 },
  { title: "Happy", artist: "Pharrell Williams", year: 2013 },
  { title: "Uptown Funk", artist: "Mark Ronson", year: 2014 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },
];
