// Curated Hitster-style song deck: title, artist, and true release year of the single.
const SONGS = [
  { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", year: 1954 },
  { title: "Hound Dog", artist: "Elvis Presley", year: 1956 },
  { title: "That'll Be the Day", artist: "Buddy Holly", year: 1957 },
  { title: "I Want to Hold Your Hand", artist: "The Beatles", year: 1963 },
  { title: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { title: "Good Vibrations", artist: "The Beach Boys", year: 1966 },
  { title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { title: "Hey Jude", artist: "The Beatles", year: 1968 },
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { title: "Hotel California", artist: "Eagles", year: 1976 },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { title: "Billie Jean", artist: "Michael Jackson", year: 1983 },
  { title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { title: "Like a Virgin", artist: "Madonna", year: 1984 },
  { title: "Take On Me", artist: "a-ha", year: 1985 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { title: "I Will Always Love You", artist: "Whitney Houston", year: 1992 },
  { title: "Wonderwall", artist: "Oasis", year: 1995 },
  { title: "...Baby One More Time", artist: "Britney Spears", year: 1998 },
  { title: "Bye Bye Bye", artist: "NSYNC", year: 2000 },
  { title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004 },
  { title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { title: "Empire State of Mind", artist: "Jay-Z", year: 2009 },
  { title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011 },
  { title: "Get Lucky", artist: "Daft Punk", year: 2013 },
  { title: "Happy", artist: "Pharrell Williams", year: 2013 },
  { title: "Uptown Funk", artist: "Mark Ronson", year: 2014 },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { title: "As It Was", artist: "Harry Styles", year: 2022 },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023 },
  { title: "Cruel Summer", artist: "Taylor Swift", year: 2019 },

  { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958 },
  { title: "La Bamba", artist: "Ritchie Valens", year: 1958 },
  { title: "You Really Got Me", artist: "The Kinks", year: 1964 },
  { title: "California Girls", artist: "The Beach Boys", year: 1965 },
  { title: "Paint It Black", artist: "The Rolling Stones", year: 1966 },
  { title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
  { title: "All Along the Watchtower", artist: "Jimi Hendrix", year: 1968 },
  { title: "Fortunate Son", artist: "Creedence Clearwater Revival", year: 1969 },
  { title: "Come Together", artist: "The Beatles", year: 1969 },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", year: 1970 },
  { title: "What's Going On", artist: "Marvin Gaye", year: 1971 },
  { title: "Imagine", artist: "John Lennon", year: 1971 },
  { title: "Superstition", artist: "Stevie Wonder", year: 1972 },
  { title: "Dream On", artist: "Aerosmith", year: 1973 },
  { title: "Killing Me Softly With His Song", artist: "Roberta Flack", year: 1973 },
  { title: "Band on the Run", artist: "Paul McCartney & Wings", year: 1974 },
  { title: "Love Will Keep Us Together", artist: "Captain & Tennille", year: 1975 },
  { title: "Le Freak", artist: "Chic", year: 1978 },
  { title: "Y.M.C.A.", artist: "Village People", year: 1978 },
  { title: "September", artist: "Earth, Wind & Fire", year: 1978 },
  { title: "My Sharona", artist: "The Knack", year: 1979 },
  { title: "Another Brick in the Wall", artist: "Pink Floyd", year: 1979 },
  { title: "Super Freak", artist: "Rick James", year: 1981 },
  { title: "Africa", artist: "Toto", year: 1982 },
  { title: "Beat It", artist: "Michael Jackson", year: 1983 },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983 },
  { title: "When Doves Cry", artist: "Prince", year: 1984 },
  { title: "Money for Nothing", artist: "Dire Straits", year: 1985 },
  { title: "Papa Don't Preach", artist: "Madonna", year: 1986 },
  { title: "With or Without You", artist: "U2", year: 1987 },
  { title: "Faith", artist: "George Michael", year: 1987 },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  { title: "Don't Worry, Be Happy", artist: "Bobby McFerrin", year: 1988 },
  { title: "Like a Prayer", artist: "Madonna", year: 1989 },
  { title: "Nothing Compares 2 U", artist: "Sinead O'Connor", year: 1990 },
  { title: "Vogue", artist: "Madonna", year: 1990 },
  { title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990 },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1992 },
  { title: "Creep", artist: "Radiohead", year: 1992 },
  { title: "Waterfalls", artist: "TLC", year: 1995 },
  { title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { title: "Macarena", artist: "Los Del Rio", year: 1996 },
  { title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { title: "MMMBop", artist: "Hanson", year: 1997 },
  { title: "My Heart Will Go On", artist: "Celine Dion", year: 1997 },
  { title: "Torn", artist: "Natalie Imbruglia", year: 1997 },
  { title: "Believe", artist: "Cher", year: 1998 },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", year: 1999 },
  { title: "No Scrubs", artist: "TLC", year: 1999 },
  { title: "Yellow", artist: "Coldplay", year: 2000 },
  { title: "Can't Get You Out of My Head", artist: "Kylie Minogue", year: 2001 },
  { title: "In the End", artist: "Linkin Park", year: 2001 },
  { title: "Toxic", artist: "Britney Spears", year: 2003 },
  { title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { title: "Numb", artist: "Linkin Park", year: 2003 },
  { title: "Yeah!", artist: "Usher", year: 2004 },
  { title: "Feel Good Inc.", artist: "Gorillaz", year: 2005 },
  { title: "SexyBack", artist: "Justin Timberlake", year: 2006 },
  { title: "Umbrella", artist: "Rihanna", year: 2007 },
  { title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { title: "I Gotta Feeling", artist: "The Black Eyed Peas", year: 2009 },
  { title: "Bad Romance", artist: "Lady Gaga", year: 2009 },
  { title: "Party Rock Anthem", artist: "LMFAO", year: 2011 },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2012 },
  { title: "Gangnam Style", artist: "Psy", year: 2012 },
  { title: "Royals", artist: "Lorde", year: 2013 },
  { title: "All About That Bass", artist: "Meghan Trainor", year: 2014 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014 },
  { title: "Hello", artist: "Adele", year: 2015 },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016 },
  { title: "Despacito", artist: "Luis Fonsi", year: 2017 },
  { title: "Havana", artist: "Camila Cabello", year: 2017 },
  { title: "God's Plan", artist: "Drake", year: 2018 },
  { title: "Someone You Loved", artist: "Lewis Capaldi", year: 2018 },
  { title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { title: "Drivers License", artist: "Olivia Rodrigo", year: 2021 },
  { title: "Good 4 U", artist: "Olivia Rodrigo", year: 2021 },
  { title: "Stay", artist: "The Kid Laroi", year: 2021 },
  { title: "Anti-Hero", artist: "Taylor Swift", year: 2022 },
  { title: "Unholy", artist: "Sam Smith", year: 2022 },
  { title: "Vampire", artist: "Olivia Rodrigo", year: 2023 },
];
